kind: Service
apiVersion: v1
metadata:
  name: loan-provider
  labels:
    app: loan-provider
    spring-deployment-id: loanprovider
spec:
  # If you are running k8s on a local dev box or using minikube, you can use type NodePort instead
  type: LoadBalancer
  ports:
#    - port: 80
    - port: 8090
      targetPort: 9090
      nodePort: 32766
      name: loan-provider
      protocol: TCP
#  type: NodePort
#  ports:
#      - port: 8080
#        targetPort: 9393
#        protocol: TCP
#        name: scdf-server
  selector:
    app: loan-provider
