kind: Service
apiVersion: v1
metadata:
  name: scdf-server
  labels:
    app: scdf-server
    spring-deployment-id: scdf
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 9393
      nodePort: 32767
      name: scdf-server
      protocol: TCP
  selector:
    app: scdf-server
